permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 龚慧芸
  weibo: http://weibo.com/gonghuiyun/profile?rightmod=1&wvr=6&mod=personinfo
  music: http://5sing.kugou.com/49729262/default.html  

# 站点信息
title: 龚慧芸的博客
description: My personal blog
url: https://gonghuiyun.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/home.png
favicon: /public/img/home.png

# google analytics 设置
ga:
  id: UA-64712754-1 
  url: gonghuiyun.github.io

# disqus 设置
disqus:
  shortname: gonghuiyun

# 主题设置，自动激活某个标签
active: 学习总结

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
